In [ ]:
import numpy as np

def unos(m,x):
    if m[x][x] != 0:
        m[x] = m[x] / m[x][x]
    else:
        for i in range(x+1, m.shape[0]):
            if m[i][x] != 0:
                m[[x, i]] = m[[i, x]]
                break
    return m

def ceros(m,x):
  for i in range(m.shape[0]):
    if i != x:
      m[i] = m[i] -m[i, x]*m[x]
  return m

m = (np.array([[2, 4, 6, 18], [4, 5, 6, 24], [3, 1, -6, 18]]))
m = m.astype(float)
for x in range(m.shape[0]):
  m = unos(m, x)
  m = ceros(m, x)

print(m)

[[ 1.   0.   0.  -1.2]
 [ 0.   1.   0.   8.4]
 [-0.  -0.   1.  -2.2]]
